### ISSUE TITLE
[meta] Road to 0.1.0 (or 3.0.0)

### ISSUE THREAD

**Issue by GeopJr** [GeopJr/Tuba#74]
I'm satisfied with the current state of Tooth and ready to make the first release:
(in no particular order)

- [x] Finish branding (#6 #28)
- [x] Go over all strings, review them and generate pot file (#75)
- [x] Update readme
- [x] Take screenshots for the store page
- [x] Website
- [x] Publish to Flathub (#15)

About the version: `2.1.0` was the dev version of Tootle that I never changed (I didn't expect it to be packaged prior to an official release), if marking the release as `0.1.0` causes problems in repos, then I guess I'll go with `3.0.0`.
